export const MICROCOPY = {
  welcomeMessage: 'Bienvenida a un espacio para ti 💜',
  welcomeSubtitle: 'Aquí podrás conversar, reflexionar y cuidar lo más importante: tus vínculos.',
  registerTitle: 'Crear mi espacio',
  registerSubtitle: 'Este será tu espacio, hecho para acompañarte',
  loginTitle: 'Bienvenida de nuevo',
  loginSubtitle: 'Ingresa tu correo y te enviaremos un código',
  codeTitle: 'Verifica tu código',
  codeSubtitle: 'Te enviamos un código a tu correo 💜',
  onboarding1Title: 'Violetta te acompaña',
  onboarding1Subtitle: 'Aquí te acompañamos a cuidar de ti y tus vínculos más importantes',
  onboarding2Title: 'Tu espacio de calma',
  onboarding2Subtitle: 'Podrás conversar, reflexionar y encontrar calma cuando lo necesites',
  onboarding3Title: 'Estás lista para comenzar 💜',
  onboarding3Subtitle: 'Tu espacio está listo. Empieza cuando te sientas preparada',
  thankYouRegister: 'Gracias, {name} 💜. Tu espacio está listo',
  welcomeBack: '¡Qué alegría verte de nuevo, {name}! 💜',
  codeSent: 'Te enviamos un código a {email}',
  codeError: 'Este código no coincide. Intenta de nuevo 💜',
  emailPlaceholder: '¿Cómo te gustaría que te llamemos?',
  privacyNote: 'Tus datos se mantendrán seguros. Solo Violetta los verá.',
};
